# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc2a28dd97a4f378ab276b4aef361e77e14ffb11089e4221e4791c19e06b6c7c095ee5698122be4b7f33f6280feebc8d77bffac7b9ad841514854be354f2b9fa

test:
  secret_key_base: 621abeb09e28d845c35a7474025111897bace939aab140b5ac48626c1122f86a196102d03646b7db1aebe178527459a2cb6c23d23d1b3a29f3ed06518ef84474

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
